console.log('%c Generated by HTML5 Slotbuilder Copyright 2025 by All-Scripts ', 'color:white; background:red',  'https://www.all-scripts.de');

let game;
let app;
let scalefactor = 1;
let loadResolution = 'middle';
const BALANCE_STORAGE_KEY = 'mjw_balance';

switch (resolution) {
	case 'low':
		scalefactor = 0.5;
		loadResolution = 'low';
		break;
	case 'high':
		scalefactor = 1.5;
		loadResolution = 'high';
		break;
	default:
		scalefactor = 1;
		loadResolution = 'middle';
}

document.addEventListener('DOMContentLoaded', () => {
	const config = {
		type: Phaser.WEBGL,
		background: 0xff0000,
		roundPixels: true,
		createContainer: true,
		antialias: true,
		fps: {
			min: 30,
			target: 30,
			forceSetTimeOut: true
		},
	    scale: {
		    mode: Phaser.Scale.FIT,
		    autoCenter: Phaser.Scale.CENTER_BOTH,
		    parent: 'game-container',
		    width: scaleResolution(1280),
		    height: scaleResolution(720)
	    },	
		scene: [
			Preloader, 
			MainGame
		]
	};

	game = new Phaser.Game(config);
});

class Preloader extends Phaser.Scene {
    constructor() {
        super({key: 'Preloader'});
    }

	preload() {
		app = this;
		app.gamecfg = {
			symbols: [],
			decimals: 0,
			symbols_total: 9,
			symbol_width: scaleResolution(183),
			symbol_height: scaleResolution(171),
			path_audio: 'assets/audio',
			path_images: 'assets/images',
			path_animations: 'assets/animations',
			remote_file: 'client-mock',
			payout_multipliers: {},
		};
		app.gamedata = {};
		app.gamedata.symbols = [];
		app.labels = {};
		app.fields = {};
		app.buttons = {};
		app.reels = {};
		app.audio = {};
		app.winlines = {};
		app.language = {};
		app.lkey = 'TVhOei1lU3JyLWFyczItZml3cw==';
		app.settings = {
			bet: 0,
			betid: 0,
			audio: 1,
			music: 1,
			autoplay: 0,
			paytable: 0,
			isplay: false,
			wlrounds: 0,
			windelay: 1000,
			audiotrack: 'normal'
		};
		app.load.setPath(app.gamecfg.path_images);

        this.load.image('preloader_background', 'preloader_background_' + loadResolution + '.webp');
        this.load.image('preloader_bar', 'preloader_bar_' + loadResolution + '.webp');
        this.load.image('preloader_mask', 'preloader_mask_' + loadResolution + '.webp');
	}
	create() {
		const fontsTypes = ['Upcfb'];
		fontsTypes.forEach((font) => {
			app.add.text(-1000, 0, 'hack', {fontFamily: font, fontSize: 80, color: "#ff0000"});
		});
		app.game.events.off('hidden', app.game.onHidden, app.game, false); 
		app.game.events.off('visible', app.game.onVisible, app.game, false);
		app.game.sound.pauseOnBlur = false;	
		for (let i = 0; i < 15; i++) {
			app.gamedata.symbols.push(Phaser.Math.Between(1, app.gamecfg.symbols_total));
		}
		fetchJSON(app.gamecfg.remote_file, {action: 'loadconfig', lang: langcode}, (json) => {
	        if (!json.error) {
	        	app.gamecfg.decimals = json.decimals;
	            app.gamecfg.symbols = json.symbols;
	            app.gamecfg.symbols_total = json.symbols.length;
	            app.gamecfg.payout_multipliers = json.payout_multipliers;
	            app.language = json.language;
	            app.winlines = json.winlines;
	        }
	    }, 'json');
        app.add.sprite(
        	scaleResolution(0), 
        	scaleResolution(0), 
        	'preloader_background'
        ).setOrigin(0);
        const preloader_bar = app.add.sprite(
        	scaleResolution(425), 
        	scaleResolution(446), 
        	'preloader_bar'
        ).setOrigin(0);        
        app.add.sprite(
        	scaleResolution(-1000), 
        	scaleResolution(-1000), 
        	'preloader_mask'
        ).setOrigin(0);
        const shape = app.make.graphics().fillRect(preloader_bar.x, preloader_bar.y, 0, preloader_bar.height);
        const mask = shape.createGeometryMask();
	    preloader_bar.setMask(mask);
	    app.load.on('progress', (value) => {
	    	shape.clear();
	    	shape.fillRect(preloader_bar.x, preloader_bar.y, preloader_bar.width / 100 * Math.round(value * 100), preloader_bar.height);
	    });
	    app.load.setPath(app.gamecfg.path_images);
		app.load.image('background', 'background_' + loadResolution + '.webp');
		app.load.image('mask', 'mask_' + loadResolution + '.webp');
		app.load.image('paytable_background', 'paytable_background_' + loadResolution + '.webp');		
		app.load.atlas('buttons', 'buttons_' + loadResolution + '.webp', 'buttons_' + loadResolution + '.json');
	    app.load.setPath(app.gamecfg.path_animations);
	    app.load.multiatlas('symbols', 'symbols_' + loadResolution + '.json', app.gamecfg.path_animations);
	    app.load.setPath(app.gamecfg.path_audio);
	    app.load.audio('audio_music', ['music.ogg', 'music.mp3']);
	    app.load.audio('audio_fsmusic', ['fsmusic.ogg', 'fsmusic.mp3']);
	    app.load.audio('audio_click', ['click.ogg', 'click.mp3']);
	    app.load.audio('audio_reel_start', ['reel_start.ogg', 'reel_start.mp3']);
	    app.load.audio('audio_reel_stop', ['reel_stop.ogg', 'reel_stop.mp3']);
	    app.load.audio('audio_win_normal', ['win_small.ogg', 'win_small.mp3']);    
	    app.load.audio('audio_win_middle', ['win_middle.ogg', 'win_middle.mp3']);    
	    app.load.audio('audio_win_big', ['win_big.ogg', 'win_big.mp3']);    
		app.load.audio('audio_win_jackpot', ['win_jackpot.ogg', 'win_jackpot.mp3']);
		app.load.audio('audio_win_freespin', ['win_freespin.ogg', 'win_freespin.mp3']);
	    app.time.addEvent({
	    	delay: 1000, 
	    	callback: () => {
	    		app.load.start();
	    	}, 
	    	callbackScope: app, 
	    	loop: false 
	    });
	    app.load.on('complete', () => {
	        app.scene.launch('MainGame');
	    });
	}
}

class MainGame extends Phaser.Scene {
    constructor() {
        super({key: 'MainGame'});
    }
    create () {
		app.game.events.off('hidden', app.game.onHidden, app.game, false); 
		app.game.events.off('visible', app.game.onVisible, app.game, false);
		app.game.sound.pauseOnBlur = false;
		app.settings.raftimer = false;
		app.game.events.on('hidden', () => {
			app.settings.raftimer = setInterval(rafTest, 1000 / 60);
		} , app);
		app.game.events.on('visible', () => {
			clearInterval(app.settings.raftimer);
		}, app);
	    app.add.sprite(scaleResolution(0), scaleResolution(0), 'background').setOrigin(0);
	    initSymbolAnimations();
	    app.reel1 = createReel(scaleResolution(143), scaleResolution(98));
	    app.reel2 = createReel(scaleResolution(346), scaleResolution(98));
	    app.reel3 = createReel(scaleResolution(547), scaleResolution(98));
	    app.reel4 = createReel(scaleResolution(751), scaleResolution(98));
	    app.reel5 = createReel(scaleResolution(952), scaleResolution(98));
	    app.add.sprite(scaleResolution(0), scaleResolution(0), 'mask').setOrigin(0);	    
	    initAudio();
	    initButtons();       
	    initLabels();
	    initFields();
		initPaytable();
		app.scale.on('leavefullscreen', checkFullScreen, app);
		fetchJSON(app.gamecfg.remote_file, {action: 'load', lang: langcode}, betUpdate, 'json');
    }
}

const rafTest = () => {
	//console.log('rafTimer');
}

const initButtons = () => {
	// FullScreen Button
	app.buttons.fullscreen = app.add.sprite(
		scaleResolution(1220), 
		scaleResolution(14), 
		'buttons', 
		'button_fullscreen_regular.webp'
	).setInteractive({
		pixelPerfect: false, 
		pixelPerfectOver: false, 
		useHandCursor: true
	}).setOrigin(0);
    app.buttons.fullscreen.on('pointerup', () => {
    	PlayAudio('click');
        if (app.scale.isFullscreen) {
            app.scale.stopFullscreen();
        } 
        else {
            app.scale.startFullscreen();
        }
    });
    app.buttons.fullscreen.on('pointerover', () => {
    	if (app.scale.isFullscreen) {
	    	app.buttons.fullscreen.show('activehover');
	    }
	    else {
	    	app.buttons.fullscreen.show('regularhover');
	    }    	
    });  
    app.buttons.fullscreen.on('pointerout', () => {
    	if (app.scale.isFullscreen) {
	    	app.buttons.fullscreen.show('active');
	    }
	    else {
	    	app.buttons.fullscreen.show('regular');
	    }
    });
    app.buttons.fullscreen.show = (type) => {
    	app.buttons.fullscreen.setTexture('buttons', `button_fullscreen_${type}.webp`);
    }    

    // SFX Button
	app.buttons.audio = app.add.sprite(
		scaleResolution(245), 
		scaleResolution(672),  
		'buttons', 
		'button_sfx_active.webp'
	).setInteractive({
		pixelPerfect: false, 
		pixelPerfectOver: false, 
		useHandCursor: true
	}).setOrigin(0);
    app.buttons.audio.on('pointerup', () => {
    	PlayAudio('click');
    	SwitchAudio();
    });
    app.buttons.audio.on('pointerover', () => {
    	if (app.settings.audio > 0) {
	    	app.buttons.audio.show('activehover');
	    }
	    else {
	    	app.buttons.audio.show('regularhover');
	    }	    
    });  
    app.buttons.audio.on('pointerout', () => {
    	if (app.settings.audio > 0) {
	    	app.buttons.audio.show('active');
	    }
	    else {
	    	app.buttons.audio.show('regular');
	    }
    });
    app.buttons.audio.show = (type) => {
    	app.buttons.audio.setTexture('buttons', `button_sfx_${type}.webp`);
    }

    // Music Button
	app.buttons.music = app.add.sprite(
		scaleResolution(198), 
		scaleResolution(672),
		'buttons', 
		'button_audio_active.webp'
	).setInteractive({
		pixelPerfect: false, 
		pixelPerfectOver: false, 
		useHandCursor: true
	}).setOrigin(0);
    app.buttons.music.on('pointerup', () => {
    	PlayAudio('click');
    	SwitchMusic();
    });
    app.buttons.music.on('pointerover', () => {	    
    	if (app.settings.music > 0) {
	    	app.buttons.music.show('activehover');
	    }
	    else {
	    	app.buttons.music.show('regularhover');
	    }	    
    });  
    app.buttons.music.on('pointerout', () => {
    	if (app.settings.music > 0) {
	    	app.buttons.music.show('active');
	    }
	    else {
	    	app.buttons.music.show('regular');
	    }
    });
    app.buttons.music.show = (type) => {
    	app.buttons.music.setTexture('buttons', `button_audio_${type}.webp`);
    }

    // Autoplay Button
	app.buttons.autoplay = app.add.sprite(
		scaleResolution(945), 
		scaleResolution(677),
		'buttons',
		'button_autoplay_regular.webp'
	).setInteractive({
		pixelPerfect: true, 
		pixelPerfectOver: true, 
		useHandCursor: true
	}).setOrigin(0);
    app.buttons.autoplay.on('pointerup', () => {
    	PlayAudio('click');
      	SwitchAutoplay(1);
    });
    app.buttons.autoplay.on('pointerover', () => {
    	if (app.settings.autoplay > 0) {
    		app.buttons.autoplay.show('activehover');
	    }
	    else {
	    	app.buttons.autoplay.show('regularhover');
	    }
    });  
    app.buttons.autoplay.on('pointerout', () => {
    	if (app.settings.autoplay > 0) {
    		app.buttons.autoplay.show('active');
	    }
	    else {
	    	app.buttons.autoplay.show('regular');
	    }
    });
    app.buttons.autoplay.show = (type) => {
    	app.buttons.autoplay.setTexture('buttons', `button_autoplay_${type}.webp`);
    }

    // Paytable Button
	app.buttons.paytable = app.add.sprite(
		scaleResolution(1070), 
		scaleResolution(677),
		'buttons',
		'button_paytable_regular.webp'
	).setInteractive({
		pixelPerfect: true, 
		pixelPerfectOver: true, 
		useHandCursor: true
	}).setOrigin(0);
    app.buttons.paytable.on('pointerup', () => {
    	PlayAudio('click');
	    app.paytable.toggle();
    });
    app.buttons.paytable.on('pointerover', () => {
		if (app.settings.paytable > 0) {
	    	app.buttons.paytable.show('activehover');
		}
		else {
			app.buttons.paytable.show('regularhover');
		}
    });  
    app.buttons.paytable.on('pointerout', () => {
    	if (app.settings.paytable > 0) {
    		app.buttons.paytable.show('active');
    	} 
    	else {
	    	app.buttons.paytable.show('regular');
	    }
    });
    app.buttons.paytable.show = (type) => {
    	app.buttons.paytable.setTexture('buttons', `button_paytable_${type}.webp`);
    }

    // Betless Button
	app.buttons.betless = app.add.sprite(
		scaleResolution(945), 
		scaleResolution(635),
		'buttons', 
		'button_betless_regular.webp'
	).setInteractive({
		pixelPerfect: true, 
		pixelPerfectOver: true, 
		useHandCursor: true
	}).setOrigin(0);
    app.buttons.betless.on('pointerup', () => {
    	PlayAudio('click');
	    if (false === app.settings.isplay) {
	    	app.buttons.betless.show('active');
			fetchJSON(app.gamecfg.remote_file, {action: 'changebet', lang: langcode, typ: 'betless', betId: app.settings.betid}, betUpdate, 'json');
	    }
    });
    app.buttons.betless.on('pointerover', () => {
	    app.buttons.betless.show('regularhover');
    });  
    app.buttons.betless.on('pointerout', () => {
	    app.buttons.betless.show('regular');
    });
    app.buttons.betless.show = (type) => {
    	app.buttons.betless.setTexture('buttons', `button_betless_${type}.webp`);
    }    

    // Betmore Button
	app.buttons.betmore = app.add.sprite(
		scaleResolution(1070), 
		scaleResolution(635),
		'buttons', 
		'button_betmore_regular.webp'
	).setInteractive({
		pixelPerfect: true, 
		pixelPerfectOver: true, 
		useHandCursor: true
	}).setOrigin(0);
    app.buttons.betmore.on('pointerup', () => {
    	PlayAudio('click');
    	if (false === app.settings.isplay) {
    		app.buttons.betmore.show('active');
			fetchJSON(app.gamecfg.remote_file, {action: 'changebet', lang: langcode, typ: 'betmore', betId: app.settings.betid}, betUpdate, 'json');    	
	    }
    });
    app.buttons.betmore.on('pointerover', () => {
	    app.buttons.betmore.show('regularhover');
    });  
    app.buttons.betmore.on('pointerout', () => {
	    app.buttons.betmore.show('regular');
    });
    app.buttons.betmore.show = (type) => {
    	app.buttons.betmore.setTexture('buttons', `button_betmore_${type}.webp`);
    }

    // Play Button
	app.buttons.play = app.add.sprite(
		scaleResolution(985), 
		scaleResolution(633),
		'buttons',
		'button_play_regular.webp'
	).setInteractive({
		pixelPerfect: true, 
		pixelPerfectOver: true, 
		useHandCursor: true
	}).setOrigin(0);
    app.buttons.play.on('pointerup', () => {
    	PlayAudio('click');
    	if (false === app.settings.isplay) {
    		PressPlay();
    		app.buttons.play.show('active');
    	}
    });	
    app.buttons.play.on('pointerover', () => {
    	if (false === app.settings.isplay) {
	    	app.buttons.play.show('regularhover');
	    }
	    else {
	    	app.buttons.play.show('activehover');
	    }
    }); 
    app.buttons.play.on('pointerout', () => {
    	if (false === app.settings.isplay) {
	    	app.buttons.play.show('regular');
	    }
	    else {
	    	app.buttons.play.show('active');
	    }
    });
    app.buttons.play.show = (type) => {
    	app.buttons.play.setTexture('buttons', `button_play_${type}.webp`);
    } 
}

const initLabels = () => {
    app.labels.fs = app.add.text(
    	scaleResolution(600), 
    	scaleResolution(690), 
    	app.language.label_fs, 
    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(26), color: '#fbb30b'}
    ).setOrigin(1, 0);

    app.labels.jackpot = app.add.text(
    	scaleResolution(760), 
    	scaleResolution(690), 
    	app.language.label_jackpot, 
    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(26), color: '#fbb30b'}
    ).setOrigin(1, 0);

    app.labels.balance = app.add.text(
    	scaleResolution(380), 
    	scaleResolution(670), 
    	app.language.label_balance, 
    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(26), color: '#fbb30b'}
    ).setOrigin(1, 0);

	app.labels.bet = app.add.text(
    	scaleResolution(380), 
    	scaleResolution(690),
		app.language.label_bet, 
    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(26), color: '#fbb30b'}
    ).setOrigin(1, 0);

    app.labels.message = app.add.text(
    	scaleResolution(600), 
    	scaleResolution(670),
    	app.language.label_message, 
    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(26), color: '#fbb30b'}
    ).setOrigin(1, 0);
}

const initFields = () => {
	app.fields.jackpot = app.add.text(
    	scaleResolution(765), 
    	scaleResolution(690),
		'',
    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(26), color: '#ffffff'}
    ).setOrigin(0, 0);

    app.fields.balance = app.add.text(
    	scaleResolution(385), 
    	scaleResolution(670),
    	'', 
    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(26), color: '#ffffff'}
    ).setOrigin(0, 0);

    app.fields.bet = app.add.text(
    	scaleResolution(385), 
    	scaleResolution(690),
    	'', 
    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(26), color: '#ffffff'}
    ).setOrigin(0, 0);

    app.fields.message = app.add.text(
    	scaleResolution(605), 
    	scaleResolution(670),
    	'', 
    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(26), color: '#ffffff'}
    ).setOrigin(0, 0);

    app.fields.fs = app.add.text(
    	scaleResolution(605), 
    	scaleResolution(690), 
    	'', 
    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(26), color: '#ffffff'}
    ).setOrigin(0, 0);
}

const initAudio = () => {
	app.audio.music = app.sound.add('audio_music', {loop: true });
	app.audio.fsmusic = app.sound.add('audio_fsmusic', {loop: true });
    app.audio.click = app.sound.add('audio_click');
    app.audio.reel_start = app.sound.add('audio_reel_start');
    app.audio.reel_stop = app.sound.add('audio_reel_stop');
    app.audio.win_normal = app.sound.add('audio_win_normal');
    app.audio.win_middle = app.sound.add('audio_win_middle');
    app.audio.win_big = app.sound.add('audio_win_big');
    app.audio.win_jackpot = app.sound.add('audio_win_jackpot');
    app.audio.win_freespin = app.sound.add('audio_win_freespin');
    app.audio.music.play();
    app.audio.music.pause();
    app.audio.fsmusic.play();
    app.audio.fsmusic.pause();    
}

const PlayAudio = (track) => {
	if (app.settings.audio > 0) {
		app.audio[track].play();
	}
}

const initSymbolAnimations = () => {
    app.gamecfg.symbols.forEach((symbol) => {
    	app.anims.create({
    		key: `sym_${symbol}_anim`, 
    		frames: app.anims.generateFrameNames('symbols', {
    			start: 0, 
    			end: 0, 
    			zeroPad: 3, 
    			prefix: `sym_${symbol}_`, 
    			suffix: '.webp'
    		}),
    		frameRate: 1
    	});	
    });
}

const initPaytable = () => {
	app.paytable = app.add.container();
	app.paytable.background = app.add.sprite(scaleResolution(136), scaleResolution(83), 'paytable_background').setOrigin(0);	
	app.paytable.add(app.paytable.background);
	app.paytable.page = 1;

	app.paytable.show = () => {
		app.settings.paytable = 1;
		app.paytable.setVisible(true);
		app.buttons.paytable.show('active');
	}
	
	app.paytable.hide = () => {
		app.settings.paytable = 0;
		app.paytable.setVisible(false);
		app.buttons.paytable.show('regular');
	}

	app.paytable.toggle = () => {
	    if (app.paytable.visible) {
	    	app.paytable.hide();	    	
	    }
	    else {
	    	app.paytable.page = 1;
	    	app.paytable.show();
	    }
	}	

	// page 1
	app.paytable.c1 = app.add.container();
	app.paytable.c1.title = app.add.text(
		scaleResolution(638), 
		scaleResolution(119), 
		app.language.paytable_page1_title, 
    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(60), color: '#E1AE3A'}
    ).setOrigin(0.5, 0);	

	const positionsSymbols = [
		[scaleResolution(170), scaleResolution(180)],
		[scaleResolution(170), scaleResolution(280)],
		[scaleResolution(170), scaleResolution(380)],
		[scaleResolution(170), scaleResolution(480)],
		[scaleResolution(490), scaleResolution(180)],
		[scaleResolution(490), scaleResolution(280)],
		[scaleResolution(490), scaleResolution(380)],
		[scaleResolution(490), scaleResolution(480)],
		[scaleResolution(810), scaleResolution(180)],
		[scaleResolution(810), scaleResolution(280)],
		[scaleResolution(810), scaleResolution(380)]
	];

	const ptFontsize = scaleResolution(22);

	const positionsLables = [
		[
			scaleResolution(270), 
			[
				scaleResolution(195), 
				scaleResolution(217), 
				scaleResolution(239)
			]
		],
		[
			scaleResolution(270), 
			[
				scaleResolution(295), 
				scaleResolution(317), 
				scaleResolution(339)
			]
		],
		[
			scaleResolution(270), 
			[
				scaleResolution(395), 
				scaleResolution(417), 
				scaleResolution(439)
			]
		],
		[
			scaleResolution(270), 
			[
				scaleResolution(495), 
				scaleResolution(517), 
				scaleResolution(539)
			]
		],
		[
			scaleResolution(590), 
			[
				scaleResolution(195), 
				scaleResolution(217), 
				scaleResolution(239)
			]
		],
		[
			scaleResolution(590), 
			[
				scaleResolution(295), 
				scaleResolution(317), 
				scaleResolution(339)
			]
		],
		[
			scaleResolution(590), 
			[
				scaleResolution(395), 
				scaleResolution(417), 
				scaleResolution(439)
			]
		],
		[
			scaleResolution(590), 
			[
				scaleResolution(495), 
				scaleResolution(517), 
				scaleResolution(539)
			]
		],
		[
			scaleResolution(910), 
			[
				scaleResolution(195), 
				scaleResolution(217), 
				scaleResolution(239)
			]
		],
		[
			scaleResolution(910), 
			[
				scaleResolution(295), 
				scaleResolution(317), 
				scaleResolution(339)
			]
		],
		[
			scaleResolution(910), 
			[
				scaleResolution(395)
			]
		],
	];

	app.paytable.c1.symbols = app.add.container();
	for (let i = 0; i < app.gamecfg.symbols_total; i++) {
		let s = app.add.sprite(positionsSymbols[i][0], positionsSymbols[i][1], 'symbols', `sym_${app.gamecfg.symbols[i]}_000.webp`).setOrigin(0);
		s.setScale(0.50);
		app.paytable.c1.symbols.add(s);
	}	

	app.paytable.c1.values = app.add.container();
	app.gamecfg.symbols.forEach((sym, index) => {
		let factor = app.add.container();
		for (i in positionsLables[index][1]) {
			const l = app.add.text(
				positionsLables[index][0], 
				positionsLables[index][1][i],
				'', 
		    	{fontFamily: 'Upcfb', fontStyle: '', fontSize: scaleResolution(22), color: '#E4A759'}
		    ).setOrigin(0, 0);
			factor.add(l);
		}
		app.paytable.c1.values.add(factor);
	});

    app.paytable.c1.add([
    	app.paytable.c1.title,
    	app.paytable.c1.symbols,
    	app.paytable.c1.values
	]);

	app.paytable.add([
		app.paytable.c1
	]);

	app.paytable.hide();
}

const betUpdate = (json) => {
    if (!json.error) {
	    app.fields.jackpot.text = NumberFormat(json.jackpot, app.gamecfg.decimals);
	    app.fields.balance.text = NumberFormat(json.userBalance, app.gamecfg.decimals);
	    app.fields.bet.text = NumberFormat(json.bet, app.gamecfg.decimals);
	    app.fields.fs.text = json.freeSpins;
	    app.fields.message.text = app.language.ready;
	    app.settings.bet = json.bet;
	    app.settings.betid = json.betId;
	    updateFactors();
	    let audiotrack = json.freeSpins > 0 ? 'freegame' : 'normal';
	    CheckMusic(audiotrack);
    }
    else {
    	app.fields.message.text = json.error;
    }
}

const updateFactors = () => {
	app.gamecfg.symbols.forEach((sym, index) => {
		switch (sym) {
			case 'Wild':
				app.paytable.c1.values.list[index].list[0].text = app.language.paytable_wild_l1;
				app.paytable.c1.values.list[index].list[1].text = app.language.paytable_wild_l2;
				app.paytable.c1.values.list[index].list[2].text = app.language.paytable_wild_l3;
				break;
			case 'JP':
				app.paytable.c1.values.list[index].list[0].text = app.language.paytable_jackpot;
				break;
			default:
				let m_arr = ['c_3', 'c_4', 'c_5'];
				for (let i in m_arr) {
					let multi = sym == 'FreeSpin' ? 1 : app.settings.bet;
					app.paytable.c1.values.list[index].list[i].text = NumberFormat(app.gamecfg.payout_multipliers[`sym_${sym}`][m_arr[i]] * multi, app.gamecfg.decimals);
				}
		}
	});
}

const checkFullScreen = () => {
	if (app.scale.isFullscreen) {
    	app.buttons.fullscreen.show('active');
    }
    else {
    	app.buttons.fullscreen.show('regular');
    }
}

const createReel = (x, y) => {
	const reel = app.add.container();
	let y1 = y;
	for (let i = 0; i < 20; i++) {
		const rand = Phaser.Math.Between(0, app.gamecfg.symbols_total - 1);
		const sym = app.add.sprite(app.gamecfg.symbol_width / 2 , y1 + (app.gamecfg.symbol_height / 2), 'symbols', `sym_${app.gamecfg.symbols[rand]}_000.webp`).setOrigin(0.5);
		reel.add(sym);
		y1 -= app.gamecfg.symbol_height;
	}
	reel.x = x;
	reel.y = +app.gamecfg.symbol_height * 2;
	reel.origy = reel.y;
 	const shape = app.make.graphics().fillRect(x, y, app.gamecfg.symbol_width, app.gamecfg.symbol_height * 3);
	const mask = shape.createGeometryMask();
    reel.setMask(mask);
	return reel;
}

const SwitchAudio = () => {
	switch (app.settings.audio) {
	    case 0:			
			app.settings.audio = 1;
			app.buttons.audio.show('active');
	        break;
	    case 1:
			app.settings.audio = 0;
			app.buttons.audio.show('regular');
	        break;
	}
}

const SwitchMusic = () => {
	switch (app.settings.music) {
	    case 0:
			app.settings.music = 1;
			app.buttons.music.show('active');
	        break;
	    case 1:
			app.settings.music = 0;
			app.buttons.music.show('regular');
	        break;
	}
	CheckMusic(app.settings.audiotrack);
}

const CheckMusic = (newtrack) => {
	switch (newtrack) {
		case 'freegame':
			app.settings.audiotrack = 'freegame';
			if (app.settings.music == 1) {
			    if (app.audio.fsmusic.isPaused) {
			    	app.audio.music.pause();
			        app.audio.fsmusic.resume();
			    }
			}
			else {
				app.audio.music.pause();
				app.audio.fsmusic.pause();
			}			
			break;
		case 'normal':
			app.settings.audiotrack = 'normal';
			if (app.settings.music == 1) {
			    if (app.audio.music.isPaused) {
			    	app.audio.music.resume();
			        app.audio.fsmusic.pause();
			    }
			}
			else {
				app.audio.music.pause();
				app.audio.fsmusic.pause();
			}			
			break;
	}
}

const SwitchAutoplay = () => {
	switch (app.settings.autoplay) {
		case 0:
			app.settings.autoplay = 1;
			app.buttons.autoplay.show('active');
			break;
		case 1:
			app.settings.autoplay = 0;
			app.buttons.autoplay.show('regular');
			break;			
	}
}

const PressPlay = () => {
	app.settings.isplay = true;
	app.fields.message.text = app.language.server_request;
	if (app.repeattimer) {
		app.repeattimer.remove(false);
	}
	stopAnimations();
	app.settings.wlrounds = 0;
	fetchJSON(app.gamecfg.remote_file, {action: 'game', lang: langcode, betId: app.settings.betid}, (json) => {
        if (!json.error) {
            app.gamedata = json;
            app.fields.balance.text = NumberFormat(app.gamedata.userBalanceBefore, app.gamecfg.decimals);
		    app.fields.jackpot.text = NumberFormat(app.gamedata.jackpotBefore, app.gamecfg.decimals);
		    app.fields.fs.text = app.gamedata.freeSpinsBefore;		    
           	PlayGame();
        }
        else {
        	app.fields.message.text = json.error;
        }
    }, 'json');
}

const reverseSymbol = (number) => {
	switch (number) {
		case 2:
			return 0;
			break;
		case 0: 
			return 2;
			break;
		default:
			return 1;
			break;
	}
}

const changeSymbol = (obj, pos, newid, option = '000') => {
	option = option === 'blur' ? '000' : option;
	obj.list[pos].setTexture('symbols', `sym_${newid}_${option}.webp`);
	obj.list[pos].symid = newid;
}

const stopAnimations = () => {
	app.reel1.list.forEach((item) => {
		item.alpha = 1;
		item.frameName = 'sym_' + item.symid + '_000.webp';
	});
	app.reel2.list.forEach((item) => {
		item.alpha = 1;
		item.frameName = 'sym_' + item.symid + '_000.webp';
	});
	app.reel3.list.forEach((item) => {
		item.alpha = 1;
		item.frameName = 'sym_' + item.symid + '_000.webp';
	});	
	app.reel4.list.forEach((item) => {
		item.alpha = 1;
		item.frameName = 'sym_' + item.symid + '_000.webp';
	});	
	app.reel5.list.forEach((item) => {
		item.alpha = 1;
		item.frameName = 'sym_' + item.symid + '_000.webp';
	});
}

const PlayGame = () => {
	app.fields.message.text = app.language.game_run;
	changeSymbol(app.reel1, 19, app.gamedata.symbols[0][0]);
	changeSymbol(app.reel1, 18, app.gamedata.symbols[0][1]);
	changeSymbol(app.reel1, 17, app.gamedata.symbols[0][2]);
	changeSymbol(app.reel2, 19, app.gamedata.symbols[1][0]);
	changeSymbol(app.reel2, 18, app.gamedata.symbols[1][1]);
	changeSymbol(app.reel2, 17, app.gamedata.symbols[1][2]);
	changeSymbol(app.reel3, 19, app.gamedata.symbols[2][0]);
	changeSymbol(app.reel3, 18, app.gamedata.symbols[2][1]);
	changeSymbol(app.reel3, 17, app.gamedata.symbols[2][2]);
	changeSymbol(app.reel4, 19, app.gamedata.symbols[3][0]);
	changeSymbol(app.reel4, 18, app.gamedata.symbols[3][1]);
	changeSymbol(app.reel4, 17, app.gamedata.symbols[3][2]);
	changeSymbol(app.reel5, 19, app.gamedata.symbols[4][0]);
	changeSymbol(app.reel5, 18, app.gamedata.symbols[4][1]);
	changeSymbol(app.reel5, 17, app.gamedata.symbols[4][2]);	
	for (let i = 3; i <= 4; i++) {
		changeSymbol(app.reel1, i, app.gamecfg.symbols[Phaser.Math.Between(0, app.gamecfg.symbols_total - 1)]);
		changeSymbol(app.reel2, i, app.gamecfg.symbols[Phaser.Math.Between(0, app.gamecfg.symbols_total - 1)]);
		changeSymbol(app.reel3, i, app.gamecfg.symbols[Phaser.Math.Between(0, app.gamecfg.symbols_total - 1)]);
		changeSymbol(app.reel4, i, app.gamecfg.symbols[Phaser.Math.Between(0, app.gamecfg.symbols_total - 1)]);
		changeSymbol(app.reel5, i, app.gamecfg.symbols[Phaser.Math.Between(0, app.gamecfg.symbols_total - 1)]);
    }
	for (let i = 4; i <= 19; i++) {
		changeSymbol(app.reel1, i, app.gamecfg.symbols[Phaser.Math.Between(0, app.gamecfg.symbols_total - 1)], 'blur');
		changeSymbol(app.reel2, i, app.gamecfg.symbols[Phaser.Math.Between(0, app.gamecfg.symbols_total - 1)], 'blur');
		changeSymbol(app.reel3, i, app.gamecfg.symbols[Phaser.Math.Between(0, app.gamecfg.symbols_total - 1)], 'blur');
		changeSymbol(app.reel4, i, app.gamecfg.symbols[Phaser.Math.Between(0, app.gamecfg.symbols_total - 1)], 'blur');
		changeSymbol(app.reel5, i, app.gamecfg.symbols[Phaser.Math.Between(0, app.gamecfg.symbols_total - 1)], 'blur');
    }
    let n = 4;
    for (let i = 14; i <= 17; i++) {
		changeSymbol(app.reel1, i, app.reel1.list[n].symid, 'blur');
		changeSymbol(app.reel2, i, app.reel1.list[n].symid, 'blur');
		changeSymbol(app.reel3, i, app.reel1.list[n].symid, 'blur');
		changeSymbol(app.reel4, i, app.reel1.list[n].symid, 'blur');
		changeSymbol(app.reel5, i, app.reel1.list[n].symid, 'blur');
		n++;
	}
	ReelRun();
}

const showWinlines = (repeat) => {
	app.reel1.list.forEach((item) => {
		item.alpha = 0.2;
	});
	app.reel2.list.forEach((item) => {
		item.alpha = 0.2;
	});
	app.reel3.list.forEach((item) => {
		item.alpha = 0.2;
	});
	app.reel4.list.forEach((item) => {
		item.alpha = 0.2;
	});
	app.reel5.list.forEach((item) => {
		item.alpha = 0.2;
	});

	app.reel1.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][0])].alpha = 1;	
	const animKeyReel1 = 'sym_' + app.reel1.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][0])].symid + '_anim';
	const animDataReel1 = app.anims.get(animKeyReel1);
	if (animDataReel1.frames.length > 1) {
		app.reel1.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][0])].play(animKeyReel1);
	}
	else {
	    app.tweens.add({
	        targets: app.reel1.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][0])],
	        scale: 0.8,
	        duration: 350,
	        ease: 'Linear',
	        yoyo: true
	    });
	}
	app.reel2.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][1])].alpha = 1;
	const animKeyReel2 = 'sym_' + app.reel2.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][1])].symid + '_anim';
	const animDataReel2 = app.anims.get(animKeyReel2);	
	if (animDataReel2.frames.length > 1) {
		app.reel2.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][1])].play(animKeyReel2);
	}
	else {
	    app.tweens.add({
	        targets: app.reel2.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][1])],
	        scale: 0.8,
	        duration: 350,
	        ease: 'Linear',
	        yoyo: true
	    });
	}
	if (app.gamedata.winningLines[app.settings.wlrounds].count > 2) {
		app.reel3.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][2])].alpha = 1;
		const animKeyReel3 = 'sym_' + app.reel3.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][2])].symid + '_anim';
		const animDataReel3 = app.anims.get(animKeyReel3);
		if (animDataReel3.frames.length > 1) {
			app.reel3.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][2])].play(animKeyReel3);
		}
		else {
		    app.tweens.add({
		        targets: app.reel3.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][2])],
		        scale: 0.8,
		        duration: 350,
		        ease: 'Linear',
		        yoyo: true
		    });
		}
		app.reel3.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][2])].play('sym_' + app.reel3.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][2])].symid + '_anim');	
	}
	if (app.gamedata.winningLines[app.settings.wlrounds].count > 3) {
		app.reel4.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][3])].alpha = 1;
		const animKeyReel4 = 'sym_' + app.reel4.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][3])].symid + '_anim';
		const animDataReel4 = app.anims.get(animKeyReel4);
		if (animDataReel4.frames.length > 1) {
			app.reel4.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][3])].play(animKeyReel4);
		}
		else {
		    app.tweens.add({
		        targets: app.reel4.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][3])],
		        scale: 0.8,
		        duration: 350,
		        ease: 'Linear',
		        yoyo: true
		    });
		}
		app.reel4.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][3])].play('sym_' + app.reel4.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][3])].symid + '_anim');		
	}
	if (app.gamedata.winningLines[app.settings.wlrounds].count > 4) {
		app.reel5.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][4])].alpha = 1;
		const animKeyReel5 = 'sym_' + app.reel5.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][4])].symid + '_anim';	
		const animDataReel5 = app.anims.get(animKeyReel5);
		if (animDataReel5.frames.length > 1) {
			app.reel5.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][4])].play(animKeyReel5);
		}
		else {
		    app.tweens.add({
		        targets: app.reel5.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][4])],
		        scale: 0.8,
		        duration: 350,
		        ease: 'Linear',
		        yoyo: true
		    });
		}
		app.reel5.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][4])].play('sym_' + app.reel5.list[reverseSymbol(app.winlines[app.gamedata.winningLines[app.settings.wlrounds].line][4])].symid + '_anim');		
	}

    if (app.gamedata.winningLines[app.settings.wlrounds].symbol == 'JP') {
    	if (repeat === false) {
	    	PlayAudio('win_jackpot');
	    }
    	app.settings.windelay = 4500;
	    app.fields.message.text = app.language.win_jackpot;
    }
    else if (app.gamedata.winningLines[app.settings.wlrounds].symbol == 'FreeSpin') {
    	if (repeat === false) {
	    	PlayAudio('win_freespin');
	    }
    	app.settings.windelay = 4500;
	    app.fields.message.text = app.language.win_fs;
    }	    
    else {
    	if (app.gamedata.winningLines[app.settings.wlrounds].count <= 3) {
    		app.settings.windelay = 1000;
	    	if (repeat === false) {
		    	PlayAudio('win_normal');
		    }    		
	    	app.fields.message.text =  `${app.language.win_regular} ${app.gamedata.winningLines[app.settings.wlrounds].win}`;
	    }
    	else if (app.gamedata.winningLines[app.settings.wlrounds].count == 4) {
    		app.settings.windelay = 1000;
	    	if (repeat === false) {
		    	PlayAudio('win_middle');
		    }    		
	    	app.fields.message.text =  `${app.language.win_regular} ${app.gamedata.winningLines[app.settings.wlrounds].win}`;
	    }
    	else if (app.gamedata.winningLines[app.settings.wlrounds].count == 5) {
	    	if (repeat === false) {
		    	PlayAudio('win_big');
		    }
    		app.settings.windelay = 1000;
	    	app.fields.message.text =  `${app.language.win_regular} ${app.gamedata.winningLines[app.settings.wlrounds].win}`;
	    }
    }
	app.settings.wlrounds++;
	app.repeattimer = app.time.addEvent({
		delay: app.settings.windelay, 
		callback: () => {
			checkWinlines(repeat);
		}, 
		callbackScope: app, 
		loop: false
	});
}

const checkWinlines = (repeat) => {
	if (app.settings.wlrounds < app.gamedata.winningLines.length) {		
		showWinlines(repeat);				
	}
	else {
		EndGame(repeat);
	}
}

const EndGame = (repeat) => {
	if (true === app.settings.isplay) {
	    app.fields.balance.text = NumberFormat(app.gamedata.userBalanceAfter, app.gamecfg.decimals);
	    app.fields.jackpot.text = NumberFormat(app.gamedata.jackpotAfter, app.gamecfg.decimals);
	    app.fields.fs.text = app.gamedata.freeSpinsAfter
    }
	app.settings.wlrounds = 0;
	app.settings.isplay = false;
	if (1 === app.settings.autoplay) {
		setTimeout(PressPlay, 500);
	}
	else {

	    let audiotrack = 'normal';
	    if (app.gamedata.freeSpinsBefore > 1) {
	    	audiotrack = 'freegame';
	    }
	    else if (app.gamedata.freeSpinsWon > 0) {
	    	audiotrack = 'freegame';
	    }
	    CheckMusic(audiotrack);

		app.buttons.play.show('regular');
		if ((app.gamedata.winningLines.length > 0) && false === app.settings.isplay) {
			checkWinlines(true);
		}		
		if (app.gamedata.winningLines.length == 0) {
			app.fields.message.text = app.language.lose;
		}
	}
}

const scaleResolution = (value) => {
	return value * scalefactor;
}

const fetchJSON = (path, postdata = null, callfunc, sendvar = null) => {
    // Static deployment uses a client-side mock backend instead of server PHP.
    const data = postdata || {};
    const action = data.action;
    let response = {};

    if (action === 'loadconfig') {
        response = {
            decimals: 0,
            symbols: [1, 2, 3, 4, 5, 6, 7, 8, 'Wild', 'JP', 'FreeSpin'],
            payout_multipliers: {
                'sym_1': {'c_3': 5, 'c_4': 20, 'c_5': 100},
                'sym_2': {'c_3': 5, 'c_4': 20, 'c_5': 100},
                'sym_3': {'c_3': 5, 'c_4': 25, 'c_5': 125},
                'sym_4': {'c_3': 5, 'c_4': 25, 'c_5': 125},
                'sym_5': {'c_3': 10, 'c_4': 50, 'c_5': 250},
                'sym_6': {'c_3': 10, 'c_4': 50, 'c_5': 250},
                'sym_7': {'c_3': 15, 'c_4': 75, 'c_5': 500},
                'sym_8': {'c_3': 20, 'c_4': 100, 'c_5': 1000},
                'sym_Wild': {'c_3': 50, 'c_4': 250, 'c_5': 2500},
                'sym_JP': {'c_3': 100, 'c_4': 500, 'c_5': 5000},
                'sym_FreeSpin': {'c_3': 2, 'c_4': 10, 'c_5': 50}
            },
            language: {
                ready: "READY",
                lose: "BET AGAIN",
                game_run: "GOOD LUCK!",
                win_regular: "WIN: ",
                win_jackpot: "JACKPOT!",
                win_fs: "FREE SPINS!",
                label_balance: "BALANCE:",
                label_bet: "BET:",
                label_jackpot: "JACKPOT:",
                label_message: "INFO:",
                label_fs: "FREE SPINS:",
                paytable_page1_title: "PAYTABLE",
                paytable_wild_l1: "WILD SYMBOL",
                paytable_wild_l2: "SUBSTITUTES ALL",
                paytable_wild_l3: "EXCEPT SCATTER",
                paytable_jackpot: "JACKPOT SYMBOL",
                server_request: "REQUESTING..."
            },
            winlines: [
                [[0, 1], [1, 1], [2, 1], [3, 1], [4, 1]], 
                [[0, 0], [1, 0], [2, 0], [3, 0], [4, 0]], 
                [[0, 2], [1, 2], [2, 2], [3, 2], [4, 2]], 
                [[0, 0], [1, 1], [2, 2], [3, 1], [4, 0]], 
                [[0, 2], [1, 1], [2, 0], [3, 1], [4, 2]]
            ]
        };
    } else if (action === 'load' || action === 'changebet') {
        let balance = parseInt(localStorage.getItem(BALANCE_STORAGE_KEY) || '5000');
        response = {
            userBalance: balance,
            jackpot: 10000,
            freeSpins: 0,
            bet: 10,
            betId: data.betId || 0,
            error: null
        };
    } else if (action === 'game') {
        let balance = parseInt(localStorage.getItem(BALANCE_STORAGE_KEY) || '5000');
        const bet = 10;
        const symbols = [1, 2, 3, 4, 5, 6, 7, 8, 'Wild', 'JP', 'FreeSpin'];
        
        const resultSymbols = [];
        for (let r = 0; r < 5; r++) {
            const reel = [];
            for (let s = 0; s < 3; s++) {
                reel.push(symbols[Math.floor(Math.random() * symbols.length)]);
            }
            resultSymbols.push(reel);
        }

        const isWin = Math.random() > 0.8;
        const winAmount = isWin ? 50 : 0;
        const newBalance = balance - bet + winAmount;
        localStorage.setItem(BALANCE_STORAGE_KEY, newBalance.toString());

        response = {
            symbols: resultSymbols,
            winningLines: isWin ? [{line: 0, count: 3, win: 50, symbol: resultSymbols[0][1]}] : [],
            winAmount: winAmount,
            userBalanceBefore: balance,
            userBalanceAfter: newBalance,
            jackpotBefore: 10000,
            jackpotAfter: 10010,
            freeSpinsBefore: 0,
            freeSpinsAfter: 0,
            freeSpinsWon: 0,
            error: null
        };
    }

    setTimeout(() => {
        if (sendvar === null) {
            callfunc(response);
        } else {
            callfunc(response, sendvar);
        }
    }, 100);
};;

const xhrPreparData = (element,key,list) => {
    list = list || [];
    if (typeof(element) == 'object') {
        for (let idx in element) {
            xhrPreparData(element[idx], key ? key + '[' + idx + ']' : idx, list);
        }
    } 
    else {
        list.push(key + '=' + encodeURIComponent(element));
    }
    return list.join('&');
};

const NumberFormat = (number, decimals, decPoint = ',', thousandsSep = '.') => {
    number = (number + '').replace(/[^0-9+\-Ee.]/g, '')
    let n = !isFinite(+number) ? 0 : +number
    let prec = !isFinite(+decimals) ? 0 : Math.abs(decimals)
    let sep = (typeof thousandsSep === 'undefined') ? ',' : thousandsSep
    let dec = (typeof decPoint === 'undefined') ? '.' : decPoint
    let s = ''
    let toFixedFix = (n, prec) => {
        let k = Math.pow(10, prec)
        return '' + (Math.round(n * k) / k).toFixed(prec)
    }
    s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.')
    if (s[0].length > 3) {
        s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep)
    }
    if ((s[1] || '').length < prec) {
        s[1] = s[1] || ''
        s[1] += new Array(prec - s[1].length + 1).join('0')
    }
    return s.join(dec)
};
